### PR TITLE
Lcov 1.11 + CocoaPod + Cobertura

### PR DESCRIPTION
**Pull request by designatednerd**
This pull request is to add lcov 1.11 (addressing #24) as well as adding support for adding the tool via CocoaPods. I've updated the README to show the appropriate instructions - the TL;DR is it's less flexible, but WAY easier to get started. 

If you do want to add CocoaPods support, please tag your repo once this is merged in with 1.0.0 and then push up to the [CocoaPods trunk](http://guides.cocoapods.org/making/getting-setup-with-trunk.html). 

Please let me know if you have any questions whatsoever.

### CODE REVIEW

**Comment by emartynov** [comment]
What are news for this pull request?

**Comment by designatednerd** [comment]
@jonreid Just updated so this can be auto-merged. Is there anything else I can do to facilitate getting this merged down?

**Comment by jonreid** [comment]
Wow, I didn't know there was activity on XcodeCoverage. This looks awesome, thanks for pinging.

**Comment by designatednerd** [comment]
You bet - let me know if there's anything I can do to help get a pod up onto trunk - The changes I'd made since originally opening the PR would mean the current version should get tagged as 1.0.2.

**Pull request merged**
